/********************************************************************
* Hades_Cint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Hades_Cint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHades_Cint();
extern void G__cpp_setup_inheritanceHades_Cint();
extern void G__cpp_setup_typetableHades_Cint();
extern void G__cpp_setup_memvarHades_Cint();
extern void G__cpp_setup_globalHades_Cint();
extern void G__cpp_setup_memfuncHades_Cint();
extern void G__cpp_setup_funcHades_Cint();
extern void G__set_cpp_environmentHades_Cint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HadesAnal.h"
#include "myClass.h"
#include "utility.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Hades_CintLN_TFile;
extern G__linked_taginfo G__Hades_CintLN_TTree;
extern G__linked_taginfo G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Hades_CintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TH1F;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TH2F;
extern G__linked_taginfo G__Hades_CintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__Hades_CintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Hades_CintLN_myClass;
extern G__linked_taginfo G__Hades_CintLN_HadesAnal;

/* STUB derived class for protected member access */
