//
// File generated by rootcint at Fri Mar 13 00:18:47 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Hades_Cint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Hades_Cint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void HadesAnal_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void HadesAnal_Dictionary();
   static void *new_HadesAnal(void *p = 0);
   static void *newArray_HadesAnal(Long_t size, void *p);
   static void delete_HadesAnal(void *p);
   static void deleteArray_HadesAnal(void *p);
   static void destruct_HadesAnal(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::HadesAnal*)
   {
      ::HadesAnal *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::HadesAnal),0);
      static ::ROOT::TGenericClassInfo 
         instance("HadesAnal", "./HadesAnal.h", 21,
                  typeid(::HadesAnal), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &HadesAnal_Dictionary, isa_proxy, 0,
                  sizeof(::HadesAnal) );
      instance.SetNew(&new_HadesAnal);
      instance.SetNewArray(&newArray_HadesAnal);
      instance.SetDelete(&delete_HadesAnal);
      instance.SetDeleteArray(&deleteArray_HadesAnal);
      instance.SetDestructor(&destruct_HadesAnal);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::HadesAnal*)
   {
      return GenerateInitInstanceLocal((::HadesAnal*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::HadesAnal*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void HadesAnal_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::HadesAnal*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_HadesAnal(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::HadesAnal : new ::HadesAnal;
   }
   static void *newArray_HadesAnal(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::HadesAnal[nElements] : new ::HadesAnal[nElements];
   }
   // Wrapper around operator delete
   static void delete_HadesAnal(void *p) {
      delete ((::HadesAnal*)p);
   }
   static void deleteArray_HadesAnal(void *p) {
      delete [] ((::HadesAnal*)p);
   }
   static void destruct_HadesAnal(void *p) {
      typedef ::HadesAnal current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::HadesAnal

/********************************************************
* Hades_Cint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableHades_Cint();

extern "C" void G__set_cpp_environmentHades_Cint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("HadesAnal.h");
  G__add_compiledheader("myClass.h");
  G__add_compiledheader("utility.h");
  G__cpp_reset_tagtableHades_Cint();
}
#include <new>
extern "C" int G__cpp_dllrevHades_Cint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* HadesAnal */
static int G__Hades_Cint_710_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   HadesAnal* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new HadesAnal((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) HadesAnal((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new HadesAnal[n];
       } else {
         p = new((void*) gvp) HadesAnal[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new HadesAnal;
       } else {
         p = new((void*) gvp) HadesAnal;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Hades_Cint_710_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HadesAnal*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Hades_Cint_710_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HadesAnal*) G__getstructoffset())->Loop((Char_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Hades_Cint_710_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((HadesAnal*) G__getstructoffset())->ReadLine((FILE*) G__int(libp->para[0]), (char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Hades_Cint_710_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HadesAnal*) G__getstructoffset())->SetWriteTree((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Hades_Cint_710_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HadesAnal*) G__getstructoffset())->SetEnergy((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Hades_Cint_710_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   HadesAnal* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new HadesAnal(*(HadesAnal*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef HadesAnal G__THadesAnal;
static int G__Hades_Cint_710_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (HadesAnal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((HadesAnal*) (soff+(sizeof(HadesAnal)*i)))->~G__THadesAnal();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (HadesAnal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((HadesAnal*) (soff))->~G__THadesAnal();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Hades_Cint_710_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   HadesAnal* dest = (HadesAnal*) G__getstructoffset();
   *dest = *(HadesAnal*) libp->para[0].ref;
   const HadesAnal& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* HadesAnal */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncHades_Cint {
 public:
  G__Sizep2memfuncHades_Cint(): p(&G__Sizep2memfuncHades_Cint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncHades_Cint::*p)();
};

size_t G__get_sizep2memfuncHades_Cint()
{
  G__Sizep2memfuncHades_Cint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceHades_Cint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal))) {
     HadesAnal *G__Lderived;
     G__Lderived=(HadesAnal*)0x1000;
     {
       myClass *G__Lpbase=(myClass*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal),G__get_linked_tagnum(&G__Hades_CintLN_myClass),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableHades_Cint() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__Hades_CintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* HadesAnal */
static void G__setup_memvarHadesAnal(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal));
   { HadesAnal *p; p=(HadesAnal*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TFile),-1,-1,4,"theOut=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,G__defined_typename("Char_t"),-1,4,"theOutFileName[64]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"WriteTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"Pen=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TFile),-1,-1,4,"f=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PID_histo)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PID_histo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->theta_p1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"theta_p1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->theta_p2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"theta_p2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->theta_p3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"theta_p3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPthmom2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"EPthmom2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMthmom3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"EMthmom3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pimthmom9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"Pimthmom9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pthmom14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"Pthmom14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pimphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pimphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pimtheta)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pimtheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimthetaCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimthetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimVerX9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimVerX9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimVerY9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimVerY9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimVerZ9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimVerZ9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimmomX9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimmomX9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimmomY9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimmomY9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimmomZ9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimmomZ9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimMomtot9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimMomtot9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMtheta)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMtheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMthetaCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMthetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMVerX3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMVerX3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMVerY3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMVerY3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMVerZ3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMVerZ3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMmomX3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMmomX3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMmomY3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMmomY3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMmomZ3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMmomZ3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMMomtot3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMMomtot3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPtheta)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPtheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPthetaCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPthetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPVerX2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPVerX2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPVerY2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPVerY2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPVerZ2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPVerZ2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPmomX2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPmomX2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPmomY2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPmomY2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPmomZ2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPmomZ2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPMomtot2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPMomtot2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pphi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ptheta)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Ptheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PthetaCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PthetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PVerX14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PVerX14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PVerY14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PVerY14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PVerZ14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PVerZ14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PmomX14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PmomX14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PmomY14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PmomY14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PmomZ14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PmomZ14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PMomtot14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PMomtot14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PMass14_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PMass14_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PimMass9_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"PimMass9_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EMMass3_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EMMass3_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EPMass2_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EPMass2_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass6)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass6=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MissingMass7)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"MissingMass7=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0thmom7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"Pi0thmom7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0Mass7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0Mass7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0momX7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0momX7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0momY7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0momY7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0momZ7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0momZ7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0Momtot7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0Momtot7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0theta)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0thetaCM)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0thetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0phi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0phi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pi0VerZ7_4pi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"Pi0VerZ7_4pi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Histo)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH2F),-1,-1,1,"Histo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ALLMass)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"ALLMass=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EpEm_OA)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"EpEm_OA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->OpnAng)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"OpnAng=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->OpenAngle)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_TH1F),-1,-1,1,"OpenAngle=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarHades_Cint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncHadesAnal(void) {
   /* HadesAnal */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal));
   G__memfunc_setup("OpenGeometry",1246,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 4, 0, "", "Gets the geometry information", (void*) NULL, 0);
   G__memfunc_setup("CreateHistos",1230,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WriteHistos",1157,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HadesAnal",865,G__Hades_Cint_710_0_4, 105, G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__Hades_Cint_710_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Loop",410,G__Hades_Cint_710_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Char_t' 0 - file", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadLine",772,G__Hades_Cint_710_0_7, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"E - - 0 - fID C - - 0 - line", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWriteTree",1223,G__Hades_Cint_710_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - f", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__Hades_Cint_710_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - en", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("HadesAnal", 865, G__Hades_Cint_710_0_10, (int) ('i'), G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal), -1, 0, 1, 1, 1, 0, "u 'HadesAnal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~HadesAnal", 991, G__Hades_Cint_710_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Hades_Cint_710_0_12, (int) ('u'), G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal), -1, 1, 1, 1, 1, 0, "u 'HadesAnal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncHades_Cint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
   G__memvar_setup((void*)(&gHadesA),85,0,0,G__get_linked_tagnum(&G__Hades_CintLN_HadesAnal),-1,-1,1,"gHadesA=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalHades_Cint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcHades_Cint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__Hades_CintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_myClass = { "myClass" , 99 , -1 };
G__linked_taginfo G__Hades_CintLN_HadesAnal = { "HadesAnal" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableHades_Cint() {
  G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__Hades_CintLN_TFile.tagnum = -1 ;
  G__Hades_CintLN_TTree.tagnum = -1 ;
  G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__Hades_CintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TH1F.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TH2F.tagnum = -1 ;
  G__Hades_CintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__Hades_CintLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__Hades_CintLN_myClass.tagnum = -1 ;
  G__Hades_CintLN_HadesAnal.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableHades_Cint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TFile);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TTree);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TH1F);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TH2F);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Hades_CintLN_myClass);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Hades_CintLN_HadesAnal),sizeof(HadesAnal),-1,1280,(char*)NULL,G__setup_memvarHadesAnal,G__setup_memfuncHadesAnal);
}
extern "C" void G__cpp_setupHades_Cint(void) {
  G__check_setup_version(30051515,"G__cpp_setupHades_Cint()");
  G__set_cpp_environmentHades_Cint();
  G__cpp_setup_tagtableHades_Cint();

  G__cpp_setup_inheritanceHades_Cint();

  G__cpp_setup_typetableHades_Cint();

  G__cpp_setup_memvarHades_Cint();

  G__cpp_setup_memfuncHades_Cint();
  G__cpp_setup_globalHades_Cint();
  G__cpp_setup_funcHades_Cint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncHades_Cint();
  return;
}
class G__cpp_setup_initHades_Cint {
  public:
    G__cpp_setup_initHades_Cint() { G__add_setup_func("Hades_Cint",(G__incsetup)(&G__cpp_setupHades_Cint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initHades_Cint() { G__remove_setup_func("Hades_Cint"); }
};
G__cpp_setup_initHades_Cint G__cpp_setup_initializerHades_Cint;

